// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { LoginType } from "tset-sharedlib/shared.types";


export default  interface User {
  _id?: string;

  accountId?: string | null;

  username?: string | null;

  displayedName?: string | null;

  publicId?: string | null;

  email?: string | null;

  password?: string | null;

  passwordCopy?:{iv:string,encryptedData:string} | null;

  recoveryKey?:{iv:string,encryptedData:string} | null;

  type?: string | null;

  options?: Record<string, any> | null;

  loginType?: LoginType | null;

  loginId?: string | null;

  profileImage?: Record<string, any> | null;

  userData?: Record<string, any> | null;

  userInfo?: Record<string, any> | null;

  canPublishPublicly?: boolean | null;

  pin?: string | null;

  plugins?: unknown | null;

  /** Default value: false */
  disabled?: boolean | null;

  /** Default value: false */
  deleted?: boolean | null;

  /** Default value: false */
  verified?: boolean | null;

  emailChangedAt?: Date | null;

  verifyEmailSentAt?: Date | null;

  dob?: unknown | null;

  quickBarCollectionId?: string | null;

  // uiprefs?: Record<string, any> | null;

  pinnedItemIds?: unknown | null;

  operationalStatus?: unknown | null;

  encEnabled?: boolean | null;

  encSettings?: null | Record<string, any>;

  updatedAt?: Date | null;

  createdAt?: Date | null;

  lastActiveAt?: Date | null;
}
