services:

  proxy:
    image: nginx:alpine
    ports:
      - '4444:80'
    volumes:
      - ./kindredly-server-personal/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./webapp:/usr/share/nginx/html:ro
    restart: 'unless-stopped'
    networks:
      - kindredly_backend
  dbmigration:
    image: kindredly-server
    profiles:
      - migrate
      - createdb
    platform: linux/x86_64
    build:
      context: ./
      dockerfile: kindredly-server-personal/Dockerfile
    environment:
      DB_AUTH_USER: postgres
      DB_AUTH_PASS: admin
      DB_DBNAME: kindredlydb
      DB_HOSTNAME: postgres
      DB_CLIENT: postgresql
      REDIS_PORT: 6379
      REDIS_HOST: redis
      NODE_ENV: development
      MIGRATE_OPTION: 
    command: >
      bash -c "/app/kindredly-server-personal/launch_migrate.sh ${MIGRATE_OPTION}"
    networks:
      - kindredly_backend
    links:
      - postgres
      - redis
    depends_on:
      - postgres
      - redis
    volumes:
      - ./:/app
      - ~/kindredly-personal-data:/root/ThetaSetData
      # - kindredly_personal_node_modules:/app/kindredly-server-personal/node_modules
  kindredly-task-server:
    image: kindredly-server
    platform: linux/x86_64
    build:
      context: ./
      dockerfile: kindredly-server-personal/Dockerfile
    command: >
      bash -c '/app/kindredly-server-personal/launch_task_runner.sh'
    environment:
      DB_AUTH_USER: postgres
      DB_AUTH_PASS: admin
      DB_DBNAME: kindredlydb
      DB_HOSTNAME: postgres
      DB_CLIENT: postgresql
      REDIS_PORT: 6379
      REDIS_HOST: redis
      NODE_ENV: development
    # ports:
    #   - '3000:3000'
    restart: 'unless-stopped'
    networks:
      - kindredly_backend
    links:
      - postgres
      - redis
    depends_on:
      - postgres
      - redis
    volumes:
      - ./:/app
      - ~/kindredly-personal-data:/root/ThetaSetData
      # - kindredly_personal_node_modules:/app/kindredly-server-personal/node_modules
  kindredly-server-personal:
    image: kindredly-server
    platform: linux/x86_64
    build:
      context: ./
      dockerfile: kindredly-server-personal/Dockerfile
    environment:
      DB_AUTH_USER: postgres
      DB_AUTH_PASS: admin
      DB_DBNAME: kindredlydb
      DB_HOSTNAME: postgres
      DB_CLIENT: postgresql
      REDIS_PORT: 6379
      REDIS_HOST: redis
      NODE_ENV: development
    command: >
      bash -c "/app/kindredly-server-personal/launch_server.sh"
    ports:
      - '3000:3000'
    restart: 'unless-stopped'
    networks:
      - kindredly_backend
    links:
      - postgres
      - redis
    depends_on:
      - postgres
      - redis
    volumes:
      - ./:/app
      - ~/kindredly-personal-data:/root/ThetaSetData
      # - kindredly_personal_node_modules:/app/kindredly-server-personal/node_modules
  redis:
    image: redis/redis-stack-server:6.2.6-v7
    environment:
      - REDIS_ARGS=--save 1200 32
      - '6379:6379'
    volumes:
      - kindredly_redis:/data
    networks:
      - kindredly_backend
  postgres:
    image: postgres:14.6-bullseye
    # container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: kindredlydb
    ports:
      - '5435:5432'
    volumes:
      - kindredly_postgres:/data
    networks:
      - kindredly_backend

networks:
  kindredly_backend:
    driver: bridge

volumes:
  kindredly_personal_node_modules:
  kindredly_postgres:
    driver: local
  kindredly_redis:
    driver: local
