import type {BannerAsset} from 'tset-sharedlib/api/api-types';

/**
 * Curated default banner library (code = source of truth).
 *
 * Each entry is generated by the admin "Banner Library" console and published
 * to image storage (S3 `thetasetappdata` in prod, ~/ThetaSetData/images locally)
 * via UserFileAccessProvider.uploadImageDirect.
 *
 * Constraints:
 *  - `filename`/`thumbFilename` must be FLAT (no slashes) — `/image/get/:filename`
 *    is an Express param and slashes break routing.
 *  - Files are served as JPEG (the route hardcodes Content-Type: image/jpeg).
 */
export type CuratedBanner = BannerAsset & {prompt: string};

/** Shared style appended to every prompt so the whole set is visually consistent. */
export const PAINTERLY_STYLE_SUFFIX =
  ' Painterly digital illustration, rich textured brushwork, soft natural lighting, ' +
  'warm inviting color palette, gentle depth, wide cinematic banner composition with ' +
  'calm open negative space on one side for a title overlay. Child-friendly and wholesome. ' +
  'No text, no words, no letters, no numbers, no logos, no watermark.';

/** Composition + safety tail shared by the non-painterly style presets. */
const COMPOSITION_TAIL =
  ' Wide cinematic banner composition with calm open negative space on one side for a ' +
  'title overlay. Child-friendly and wholesome. No text, no words, no letters, no numbers, ' +
  'no logos, no watermark.';

export const DEFAULT_NEGATIVE_PROMPT =
  'text, words, letters, numbers, captions, watermark, signature, logo, frame, border, blurry, low quality, deformed';

/**
 * Named style presets the admin can pick per banner. Only `{id, name}` is exposed
 * to the client; `promptSuffix` and `negativePrompt` stay server-side and are
 * applied at generation time. `painterly` is the default and reproduces the
 * original look exactly.
 */
export type BannerStyleDef = {id: string; name: string; promptSuffix: string; negativePrompt: string};

export const DEFAULT_BANNER_STYLE_ID = 'painterly';

export const BANNER_STYLES: BannerStyleDef[] = [
  {
    id: 'painterly',
    name: 'Painterly',
    promptSuffix: PAINTERLY_STYLE_SUFFIX,
    negativePrompt: DEFAULT_NEGATIVE_PROMPT,
  },
  {
    id: 'watercolor',
    name: 'Watercolor',
    promptSuffix:
      ' Soft watercolor painting, delicate translucent washes, gentle bleeding pigments, ' +
      'light paper texture, airy pastel palette.' +
      COMPOSITION_TAIL,
    negativePrompt: DEFAULT_NEGATIVE_PROMPT,
  },
  {
    id: 'storybook',
    name: 'Storybook',
    promptSuffix:
      " Whimsical children's storybook illustration, hand-drawn ink linework, flat gouache " +
      'shading, cozy charming mood.' +
      COMPOSITION_TAIL,
    negativePrompt: DEFAULT_NEGATIVE_PROMPT,
  },
  {
    id: 'flat-vector',
    name: 'Flat vector',
    promptSuffix:
      ' Clean flat vector illustration, bold simple shapes, smooth gradients, minimal modern ' +
      'design, bright friendly colors.' +
      COMPOSITION_TAIL,
    negativePrompt: DEFAULT_NEGATIVE_PROMPT + ', photorealistic, 3d render, noisy texture',
  },
  {
    id: 'photographic',
    name: 'Photographic',
    promptSuffix:
      ' Photorealistic cinematic photograph, natural lighting, shallow depth of field, rich ' +
      'detail, vibrant yet natural color.' +
      COMPOSITION_TAIL,
    negativePrompt: DEFAULT_NEGATIVE_PROMPT + ', illustration, cartoon, painting, drawing',
  },
  {
    id: 'anime',
    name: 'Anime',
    promptSuffix:
      ' Anime-style digital illustration, clean cel shading, expressive vibrant colors, soft ' +
      'gradients, detailed background art.' +
      COMPOSITION_TAIL,
    negativePrompt: DEFAULT_NEGATIVE_PROMPT,
  },
];

/** Resolve a style by id, falling back to the default (painterly). */
export function styleById(id?: string): BannerStyleDef {
  return BANNER_STYLES.find((s) => s.id === id) ?? BANNER_STYLES[0];
}

/** Public catalog projection — drops the admin-only `prompt` field. */
export function toPublicBanner({prompt, ...asset}: CuratedBanner): BannerAsset {
  void prompt;
  return asset;
}

function banner(category: string, slug: string, title: string, tags: string[], prompt: string): CuratedBanner {
  const base = `banner-${category}-${slug}`;
  return {
    id: `${category}-${slug}`,
    title,
    filename: `${base}.jpg`,
    thumbFilename: `${base}-thumb.jpg`,
    categories: [category],
    tags: [category, ...tags],
    prompt,
  };
}

export const CURATED_BANNERS: CuratedBanner[] = [
  // Animals
  banner(
    'animals',
    'savanna',
    'Savanna Lion',
    ['lion', 'safari', 'gold', 'warm'],
    'A majestic lion resting on a golden savanna at sunrise, acacia trees in the distance.',
  ),
  banner(
    'animals',
    'rainforest',
    'Rainforest Friends',
    ['toucan', 'monkey', 'jungle', 'green'],
    'A colorful toucan and playful monkeys among lush rainforest leaves.',
  ),
  banner(
    'animals',
    'ocean',
    'Sea Turtle',
    ['turtle', 'sea', 'reef', 'blue'],
    'A graceful sea turtle gliding through sunlit turquoise ocean water with tropical fish.',
  ),

  // Space
  banner(
    'space',
    'nebula',
    'Purple Nebula',
    ['nebula', 'stars', 'cosmic', 'purple'],
    'A glowing purple and blue nebula with swirling stars and distant galaxies.',
  ),
  banner(
    'space',
    'planets',
    'Planets',
    ['planets', 'solar', 'ringed', 'colorful'],
    'A row of colorful planets and a ringed gas giant floating in deep space.',
  ),
  banner(
    'space',
    'rocket',
    'Rocket to the Moon',
    ['rocket', 'moon', 'launch', 'adventure'],
    'A friendly rocket ship soaring past the moon toward bright stars.',
  ),

  // Nature
  banner(
    'nature',
    'forest',
    'Sunlit Forest',
    ['forest', 'trees', 'calm', 'green'],
    'A peaceful green forest with tall trees and soft sunbeams filtering through the canopy.',
  ),
  banner(
    'nature',
    'mountains',
    'Alpine Lake',
    ['mountains', 'lake', 'dawn', 'snow'],
    'Snow-capped mountains reflected in a calm alpine lake at dawn.',
  ),
  banner(
    'nature',
    'meadow',
    'Wildflower Meadow',
    ['meadow', 'flowers', 'hills', 'sunny'],
    'A sunny wildflower meadow with rolling hills and a clear blue sky.',
  ),

  // Sports
  banner(
    'sports',
    'soccer',
    'Soccer Field',
    ['soccer', 'football', 'stadium', 'green'],
    'A soccer ball on a green field with a stadium glowing at golden hour.',
  ),
  banner(
    'sports',
    'basketball',
    'Basketball',
    ['basketball', 'court', 'hoop', 'sunset'],
    'A basketball arcing toward a hoop on an outdoor court at sunset.',
  ),
  banner(
    'sports',
    'cycling',
    'Cycling Trail',
    ['cycling', 'bicycle', 'trail', 'hills'],
    'A winding bicycle trail through green hills under a bright sky.',
  ),

  // Music
  banner(
    'music',
    'notes',
    'Musical Notes',
    ['notes', 'melody', 'sky', 'warm'],
    'Flowing musical notes and instruments drifting across a warm gradient sky.',
  ),
  banner(
    'music',
    'guitar',
    'Acoustic Guitar',
    ['guitar', 'acoustic', 'cozy', 'window'],
    'An acoustic guitar resting against a cozy sunlit window.',
  ),
  banner(
    'music',
    'concert',
    'Concert Lights',
    ['concert', 'stage', 'lights', 'glow'],
    'A glowing concert stage with soft colorful lights and a gentle haze.',
  ),

  // Art
  banner(
    'art',
    'palette',
    'Painter Palette',
    ['palette', 'paint', 'brushes', 'vibrant'],
    "An artist's palette with vibrant swirls of paint and brushes.",
  ),
  banner(
    'art',
    'abstract',
    'Soft Abstract',
    ['abstract', 'gradient', 'pastel', 'minimal'],
    'Soft abstract shapes and gentle gradients in pastel colors.',
  ),
  banner(
    'art',
    'easel',
    'Art Studio',
    ['easel', 'studio', 'canvas', 'bright'],
    "A painter's easel in a bright studio with canvases and warm light.",
  ),

  // Science
  banner(
    'science',
    'lab',
    'Bright Lab',
    ['lab', 'beakers', 'chemistry', 'colorful'],
    'Colorful beakers and flasks with bubbling liquids in a bright laboratory.',
  ),
  banner(
    'science',
    'atom',
    'Atom',
    ['atom', 'physics', 'particles', 'blue'],
    'A glowing atom model with orbiting particles on a deep blue background.',
  ),
  banner(
    'science',
    'microscope',
    'Microscope',
    ['microscope', 'biology', 'specimens', 'clean'],
    'A microscope and scattered specimens on a clean, bright science desk.',
  ),

  // Books / reading
  banner(
    'books',
    'library',
    'Cozy Library',
    ['library', 'shelves', 'reading', 'warm'],
    'A cozy library with tall shelves of colorful books and warm lamplight.',
  ),
  banner(
    'books',
    'stack',
    'Book Stack',
    ['books', 'stack', 'reading', 'wooden'],
    'A neat stack of well-loved books beside a steaming cup on a wooden table.',
  ),
  banner(
    'books',
    'open',
    'Storybook',
    ['storybook', 'magic', 'pages', 'glow'],
    'An open storybook with soft magical light rising gently from its pages.',
  ),

  // Math
  banner(
    'math',
    'geometry',
    'Geometry',
    ['geometry', 'shapes', 'numbers', 'blue'],
    'Floating geometric shapes and numbers in a soft blue gradient space.',
  ),
  banner(
    'math',
    'chalkboard',
    'Chalkboard',
    ['chalkboard', 'equations', 'school', 'classic'],
    'A chalkboard filled with elegant equations and geometric drawings.',
  ),
  banner(
    'math',
    'blocks',
    'Number Blocks',
    ['abacus', 'counting', 'blocks', 'colorful'],
    'A colorful abacus and number blocks arranged on a bright desk.',
  ),

  // Gaming
  banner(
    'gaming',
    'arcade',
    'Retro Arcade',
    ['arcade', 'retro', 'neon', 'cabinets'],
    'A retro arcade scene with glowing game cabinets and neon lights.',
  ),
  banner(
    'gaming',
    'controller',
    'Game Controller',
    ['controller', 'pixels', 'play', 'fun'],
    'A game controller surrounded by floating pixel hearts and stars.',
  ),
  banner(
    'gaming',
    'fantasy',
    'Fantasy World',
    ['fantasy', 'islands', 'castle', 'whimsical'],
    'A whimsical fantasy game landscape with floating islands and a distant castle.',
  ),

  // Food
  banner(
    'food',
    'fruit',
    'Fresh Fruit',
    ['fruit', 'fresh', 'healthy', 'rustic'],
    'A vibrant arrangement of fresh fruit on a rustic wooden table.',
  ),
  banner(
    'food',
    'baking',
    'Baking',
    ['baking', 'bread', 'pastries', 'kitchen'],
    'Freshly baked bread and pastries on a warm, sunlit kitchen counter.',
  ),
  banner(
    'food',
    'picnic',
    'Picnic',
    ['picnic', 'park', 'basket', 'sunny'],
    'A sunny picnic blanket with baskets of food in a green park.',
  ),

  // Vehicles
  banner(
    'vehicles',
    'cars',
    'Cars',
    ['cars', 'road', 'travel', 'colorful'],
    'Colorful cartoon cars on a winding road through rolling hills.',
  ),
  banner(
    'vehicles',
    'train',
    'Train',
    ['train', 'railway', 'countryside', 'journey'],
    'A cheerful train traveling across a countryside bridge at golden hour.',
  ),
  banner(
    'vehicles',
    'plane',
    'Airplane',
    ['plane', 'flight', 'clouds', 'sky'],
    'A small airplane flying above fluffy clouds toward a bright horizon.',
  ),
];

/** Public catalog (no prompts) — precomputed once for the search route. */
export const PUBLIC_BANNERS: BannerAsset[] = CURATED_BANNERS.map(toPublicBanner);

/** Human labels for the seed categories (fallback = Title Case of the key). */
const CURATED_CATEGORY_LABELS: Record<string, string> = {
  animals: 'Animals',
  space: 'Space',
  nature: 'Nature',
  sports: 'Sports',
  music: 'Music',
  art: 'Art',
  science: 'Science',
  books: 'Books',
  math: 'Math',
  gaming: 'Gaming',
  food: 'Food',
  vehicles: 'Vehicles',
};

/**
 * Standalone seed of the category list, derived once from CURATED_BANNERS so the
 * category structure persists even when no seed banners are materialized into the
 * catalog (banners are opt-in suggestions; categories are always present).
 */
/**
 * Reserved bucket for images imported ad-hoc (e.g. assigned to an item from a remote
 * source search) that haven't been categorized yet. Banners whose only category is
 * this key are hidden from the consumer picker and the default admin Library grid;
 * they surface only under the explicit "Unassigned" filter until an admin re-categorizes.
 */
export const UNASSIGNED_CATEGORY_KEY = 'unassigned';
export const UNASSIGNED_CATEGORY_LABEL = 'Unassigned';

export const CURATED_CATEGORIES: {key: string; label: string}[] = (() => {
  const keys = new Set<string>();
  for (const b of CURATED_BANNERS) for (const k of b.categories) keys.add(k);
  return [...keys].map((key) => ({
    key,
    label: CURATED_CATEGORY_LABELS[key] || key.replace(/^\w/, (c) => c.toUpperCase()),
  }));
})();
